### ISSUE TITLE
New open beta 12

### ISSUE THREAD

**Issue by russel5** [vm03/payload_dumper#21]
When I'm try to extract payload.bin from new open beta 12 zip for Oneplus 9 pro, it fails. No matter ColorOS or Oxygen the errors always a same.
`Processing my_heytap partition...........................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "D:\Oneplus9pro\payload_dumper-master\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "D:\Oneplus9pro\payload_dumper-master\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "D:\Oneplus9pro\payload_dumper-master\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder`

Can you check this. Thanks

**Comment by kacskrz** [comment]
Same issue with Xiaomi 12 Pro ROM (for vendor partition, others are being unpacked fine).

**Comment by xiaocang** [comment]
I found there may be an overflow in python

**Comment by GiorgioUghini** [comment]
> I found there may be an overflow in python, and my `payload.bin` file is more than 4GB

How did you solve this? @xiaocang

**Comment by Swarvey** [comment]
Same issue here during extraction of vendor.img from Xiaomi K40 Gaming (ares) miui_ARES_V13.0.5.1.28.DEV_ba4d5441b7_12.0

**Comment by rlees85** [comment]
Has anyone found a solution to this?
