### ISSUE TITLE
Error import update_metadata_pb2 as um

### ISSUE THREAD

**Issue by hammad2224** [vm03/payload_dumper#23]
All the below commands worked and installed fine
python.exe -m pip install --upgrade pip
python -m pip install protobuf
python -m pip install -r requirements.txt

When i run this
python.exe payload_dumper.py payload.bin

Traceback (most recent call last):
  File "C:\Users\hamma\AppData\Local\Programs\Python\Python310\payload_dumper.py", line 15, in <module>
    import update_metadata_pb2 as um
  File "C:\Users\hamma\AppData\Local\Programs\Python\Python310\update_metadata_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "C:\Users\hamma\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "C:\Users\hamma\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\internal\python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "C:\Users\hamma\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\internal\containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by hammad2224** [comment]
if someone gets this error then install python 3.7.4 (32bit)
that should fix the issue
