### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by hellisabove** [vm03/payload_dumper#27]
Traceback (most recent call last):
  File "/home/fucker/Downloads/payload_dumper/payload_dumper.py", line 12, in <module>
    import update_metadata_pb2 as um
  File "/home/fucker/Downloads/payload_dumper/update_metadata_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/fucker/.local/lib/python3.10/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/home/fucker/.local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "/home/fucker/.local/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by raman047** [comment]
I'm getting this issue while using the command "python payload_dumper.py payload.bin"... I'm using python 3.10

**Comment by iamra** [comment]
I am getting the same error message as well. I am on 3.10.1

**Comment by rnayabed** [comment]
This is because `collections.MutableMapping` was deprecated in Python 3.9 and was removed altogether from python 3.10

There are two ways to fix this:
1. Downgrade to Python 3.9 (Easiest)
2. Find `import collections` and replace it with `import collections.abc as collections` in the following files:
    - `<python lib folder>/python3.10/site-packages/google/protobuf/internal/well_known_types.py`
    - `<python lib folder>/python3.10/site-packages/google/protobuf/internal/containers.py`

**Comment by rnayabed** [comment]
Also did a small PR that fixes the issue. 
Waiting for inputs from @vm03 ^^
