### ISSUE TITLE
Error while unpacking vendor

### ISSUE THREAD

**Issue by anonymous-july** [vm03/payload_dumper#31]
Traceback (most recent call last):
  File "payload_dumper.py", line 163, in <module>
    dump_part(partition[0])
  File "payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder

**Comment by sevensevenmi** [comment]
cent call last):
  File "payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder

**Comment by inglar** [comment]
I have the same error
```
Processing boot partitionTraceback (most recent call last):
  File "/app/payload_dumper.py", line 163, in <module>
    dump_part(partition[0])
  File "/app/payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "/app/payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
```
