### ISSUE TITLE
Cannot decompress Redmi K50 MIUI 13 payload bin

### ISSUE THREAD

**Issue by cloudwindy** [vm03/payload_dumper#45]
```
Traceback (most recent call last):
  File "/home/skey/repo/payload_dumper/payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "/home/skey/repo/payload_dumper/payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "/home/skey/repo/payload_dumper/payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by cloudwindy** [comment]
dup #31
