### ISSUE TITLE
_lzma.LZMAError: Input format not supported by decoder

### ISSUE THREAD

**Issue by JReming85** [vm03/payload_dumper#47]
Trying to dump a full OTA for OP10, Android 13 and I keep getting this error.

.............................Traceback (most recent call last):
  File "D:\payload_dumper\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "D:\payload_dumper\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "D:\payload_dumper\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
PS D:\payload_dumper>

![image](https://user-images.githubusercontent.com/21246660/200466344-e2d53510-871e-4167-8189-aa2312b3e8ad.png)

**Comment by JReming85** [comment]
Looks like dupe of #31

**Comment by boydaihungst** [comment]
T got the same error. Search some others tool but still not work. Only this tool is working for me: https://github.com/ssut/payload-dumper-go
