### ISSUE TITLE
Extraction fails with `lzma.LZMAError: Input format not supported by decoder`

### ISSUE THREAD

**Issue by crazystylus** [vm03/payload_dumper#52]
I am unable to extract the `payload.bin` from the firmware `ColorOS 13 F.13` which is meant for `instantnoodlep`. There are no issues when extracting the same using other tools like https://github.com/ssut/payload-dumper-go or https://github.com/crazystylus/otadump

```
Processing my_stock partition...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "payload_dumper/payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "payload_dumper/payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "payload_dumper/payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by gshmu** [comment]
ectract miui_DAUMIER_V14.0.7.0.TLGCNXM_d53e0f5903_13.0.zip payload.bin
```
Processing system partition......................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "/Users/gshmu/aoe/orz/payload_dumper/payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "/Users/gshmu/aoe/orz/payload_dumper/payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshmu/aoe/orz/payload_dumper/payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
           ^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by crazystylus** [comment]
Hi @gshmu ,
Can you try extracting the same zip using [`otadump`](https://github.com/crazystylus/otadump)?

`otadump` performs multiple hash validations, so if there is something wrong with the `zip` you will get a hash mismatch or unsupported operation.


**Reference:** https://github.com/crazystylus/otadump#features

**Comment by SantaSpeen** [comment]
Такая же проблема, прошивка: `RMX3301_ROLL_BACK_Android12_EU.zip`; URL: `https://download.c.realme.com/flash/DP1_Android_13/EU/RMX3301_ROLL_BACK_Android12_EU.zip`
Processing my_product partition.................................................................................Traceback (most recent call last):
  File "C:\Users\Santa\Downloads\bin\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "C:\Users\Santa\Downloads\bin\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "C:\Users\Santa\Downloads\bin\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by Swap-File** [comment]
I fixed it here:  https://github.com/Swap-File/update_payload_extractor
