### ISSUE TITLE
hyperos rom

### ISSUE THREAD

**Issue by bouyhy1989** [vm03/payload_dumper#64]
File "C:\Python312\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "C:\Python312\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
           ^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder

**Comment by 2435043xia** [comment]
same error, rom version miui-HOUJI-OS1.0.24.0.UNCCNXM
 File "/app/payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "/app/payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "/app/payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder

**Comment by cyear** [comment]
Processing system_ext partition........................................................................Traceback (most recent call last):
  File "C:\Users\12742\Desktop\app\payload_dumper\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "C:\Users\12742\Desktop\程序\payload_dumper\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\12742\Desktop\app\payload_dumper\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
           ^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder
